### PR TITLE
Update navigation component to accommodate large part lists

### LINKED ISSUE #338: Update data entry navigation design for long list of parties
In the election for House of Representatives (Tweede Kamer), sometimes more than 30 parties participate. This does not fit well into the navigation structure we currently have for the input screens. Therefore, we will adjust the navigation menu as follows:

- The items before the lists are fixed at the top of the navigation column.
- The item 'check and save' is fixed at the bottom of the navigation column.
- The section with lists is scrollable.
- After each navigation action (via 'next' or via the navigation menu), we ensure that the active step is visible (`scrollIntoView`).
- As long as the list is not completely scrolled to the top (`scrollPosition > Scrolltop`), we show a fadeout at the top of the list.
- As long as the list is not completely scrolled to the bottom (`scrollPosition + height < scrollBottom`), we show a fadeout at the bottom of the list.

[Design in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=4927-36061&node-type=SECTION&t=yrnZQIcxc8CMyLZF-11)

### PR DESCRIPTION
**Pull request by lkleuver**
In the election for House of Representatives (Tweede Kamer), sometimes more than 30 parties participate. This does not fit well into the navigation structure we currently have for the input screens. Therefore, we will adjust the navigation menu as follows:

The items before the lists are fixed at the top of the navigation column.
The item 'check and save' is fixed at the bottom of the navigation column.
The section with lists is scrollable.
After each navigation action (via 'next' or via the navigation menu), we ensure that the active step is visible (scrollIntoView).
As long as the list is not completely scrolled to the top (scrollPosition > Scrolltop), we show a fadeout at the top of the list.
As long as the list is not completely scrolled to the bottom (scrollPosition + height < scrollBottom), we show a fadeout at the bottom of the list.

closes #338

### CODE REVIEW

**Comment by jschuurk-kr** [comment]
When I go to the page of "Lijst 1" the page scrolls down so I can't see the page title or the input field for the first candidate:
image

Tested on Firefox, Ubuntu 24.04.

**Review by jschuurk-kr — CHANGES_REQUESTED** [review]
Am getting some odd scroll behaviors on Firefox Ubuntu 24.04. See other comment for examples.

**Comment by jorisleker** [comment]
One additional finding (chrome iOS):
- if I get to the bottom of the page, the footer appears to scroll into view by itself, instead of being a part of the page.

**Review by jorisleker — CHANGES_REQUESTED** [review]
see last comment

**Comment by Lionqueen94** [comment]
https://github.com/user-attachments/assets/764ee604-ab31-4921-9884-bb204a5431c5

To me it looks good, there is just slightly weird behaviour when you have a short candidate list and a lot of lists. When I scroll down, I expect the footer to show (or arguably on short lists, the footer should already show by default), but you have to scroll quite a bit for that to happen. See the screencast added above

**Comment by jorisleker** [comment]
Discussed / decided after stand-up this morning:
- to simplify implementation, we will remove the footer on data-entry pages, because it does not really serve a purpose there. Footer will remain on other pages
- scroll into view behavior: change so the item will scroll into view only when active item is outside of the viewport (current implementation always scrolls active item to top). Desired behavior is that scroll into view makes the smallest possible scroll to get the active item into the viewport

**Comment by jschuurk-kr** [comment]
Tested on on Firefox, Ubuntu 24.04.

**Finding 6** Sometimes when I scroll down in the panel with the lists, it scrolls up. This does require that you keep scrolling even after the last list is shown. Seems easier to reproduce if you try to get the longest scroll possible from the scroll wheel of your mouse.

**Finding 7** Scrolling through the panel of the lists lets you scroll through the page as well, after you scroll to the first or last list in the panel. Sometimes there's a hiccup in that scroll of the page. Sometimes the page does not scroll up until you've scrolled up multiple times after you've scrolled up until the first list is visible in the panel.

**Finding 8** If I fill in the first six lists, go to the page of list 1, then scroll down on that page, then return to list 6, the top nav bar is not shown. If I then go to the page of list 5, the page scrolls up further, showing the top nav bar. Sometimes you have to go one list higher (so 4 in this example) before the page scrolls up completely.

**Comment by jschuurk-kr** [comment]
@lkleuver @jorisleker I can still get some weird behavior from the page, see [this comment](https://github.com/kiesraad/abacus/pull/448#issuecomment-2426932846).

Am not happy about that behavior, but am also worried this might lead into a very deep rabbit hole. So let's do another post-standup discussion?

**Review by jorisleker — DISMISSED** [review]
Tested:
- when moving forward through the parties, list scrolls up so active item is visible at bottom of viewport of container
- when moving back through the parties (with back button of browser), list scrolls down so active item is visible at top of viewport of container.

**Comment by jschuurk-kr** [comment]
@lkleuver Am still getting the issue [described here](https://github.com/kiesraad/abacus/pull/448#issuecomment-2426932846) as finding 8.

**Review by jorisleker — DISMISSED** [review]

**Review by jorisleker — APPROVED** [review]

**Review by jschuurk-kr — APPROVED** [review]

**Pull request merged**
