### PR TITLE
Added coloring of links as designed

### LINKED ISSUE #285: Inconsistent link colors and override of visited link color in feedback and alert components
We've reviewed the colors of our link styles to make them pass accessibility requirements.

The colors should be updated as follows:
- [x] link default: #155EEF 
- [x] link hover: #004EEB
- [x] link active: #0040C1
- [x] link visited: #6927DA

Also see [definition in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=3087-58933&node-type=FRAME&m=dev)

The colors apply for all links in texts (not in buttons).

There is one exception. In [feedback](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=136-2286&node-type=FRAME&m=dev) and [alert](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=985-19666&node-type=FRAME&m=dev) components (red/yellow/green or blue background) the _visited_ state of links should use the same color as the default state. Hover and active colors should override the visited color.

Acceptance criteria:
- [x] color of links adhere to scheme defined in this ticket
- [x] style of visited links in `feedback` and `alert` elements is same as non visited links
- [x] hover and active states always override visited state
- [x] style of visited links on `Controleren en opslaan` page is same as non visited links

Example of link in feedback component [in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=3085-18418&node-type=FRAME&t=yrnZQIcxc8CMyLZF-11)

### PR DESCRIPTION
**Pull request by Lionqueen94**
Related to #322 do not merge before #322 is merged to be able to test the links on the `Controleren en opslaan` page
Closes #285 

## TODO:
- [x] color of links adhere to scheme defined in this ticket
- [x] style of visited links in `feedback` and `alert` elements is same as non visited links
- [x] hover and active states always override visited state
- [x] style of visited links on `Controleren en opslaan` page is same as non visited links

### CODE REVIEW

**Review by praseodym — CHANGES_REQUESTED** [review]
The data entry page now looks like this:

Screenshot 2024-09-10 at 16 12 36

**Comment by Lionqueen94** [comment]
@jorisleker Can you have a look at this implementation and let me know if it is how you designed it? Do you want the default link in the feedback to be underlined or not for example?

**Review by jorisleker — COMMENTED** [review]
My bad, should have described desired behavior a bit better:
- Links in navigation menu's (i.e.: global nav bar at top of page) should not have the default hover / visited behavior). They now turn blue + underline on hover.
- Links in alert/feedback components should be underlined

Everything else LGTM!

**Review by jorisleker — DISMISSED** [review]

**Comment by jschuurk-kr** [comment]
@Lionqueen94 Did you take my [comment on a different issue](https://github.com/kiesraad/abacus/pull/322#issuecomment-2342850919) into account that links tend to look visited since they refer to a page that was already visited?

Apologies for not making the time to check this myself in this PR.

**Comment by jorisleker** [comment]
> > > @Lionqueen94 Did you take my [comment on a different issue](https://github.com/kiesraad/abacus/pull/322#issuecomment-2342850919) into account that links tend to look visited since they refer to a page that was already visited?
> > > Apologies for not making the time to check this myself in this PR.
> > 
> > 
> > Yes that's the final todo I added in the description ^^
> 
> Is that todo still in scope for this PR?

Might be easier to implement that change in #322, or do you want to wait till 322 is merged?

**Comment by praseodym** [comment]
We just discussed that @Lionqueen94 wants to wait for #322 to be merged.

**Review by jorisleker — APPROVED** [review]

**Review by praseodym — APPROVED** [review]

**Pull request merged**
