### PR TITLE
Don't wait for debounce when input is correct

### LINKED ISSUE #234: Improve polling station selection for fast users
## issue description
Steps:
1. Go to the polling station selection screen
2. Enter a valid polling station number
3. While "aan het zoeken..." is being displayed, click "Beginnen"

Result:
- Error is shown "Voer een geldig nummer van een stembureau in om te beginnen"
- As soon as the polling station is found, its name is shown in a green bar next to the input field.
- User remains on the polling station selection screen

image

At this point, my first reaction was to click the green bar to get to the first data entry screen. That does not work. Only later did I realize that clicking "Beginnen" would get me to the data entry page.

## summary of discussion in Mattermost
- disabling the "Beginnen" button during the search is not an option because accessibility
- the 500ms debounce is rather slow compared to the previous 200ms
- an option is to remove the error after the debounce, although that would still require the user to click "Beginnen" twice

### PR DESCRIPTION
**Pull request by cikzh**
Closes #234 

Please test if the behavior is as discussed in the issue

### CODE REVIEW

**Review by jorisleker — CHANGES_REQUESTED** [review]
Works as designed/requested if you enter a valid polling station number

If you enter an invalid number and submit with shift+enter, the red warning above the submit button is shown immediately (✅ ), but the 'aan het zoeken' message still waits for the debounce (❌ ). 

Requested change: replace the 'aan het zoeken' message with 'not found' message, if the user presses the 'beginnen' button before the debounce was finished (and the system knows the number is invalid)

**Comment by praseodym** [comment]
@jorisleker oops, I clicked re-request review by accident (I meant to click it on #267).

**Comment by cikzh** [comment]
@jorisleker I'll ping you on Mattermost when this is actually ready for review then :)

**Review by jorisleker — APPROVED** [review]
LGTM!

**Review by praseodym — APPROVED** [review]

**Pull request merged**
