### PR TITLE
Add eslint-plugin-import to lint imports and exports

### PR DESCRIPTION
**Pull request by jschuurk-kr**
https://www.npmjs.com/package/eslint-plugin-import

ToDo:
- [x]  address import/no-unresolved error
See https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#typescript for the solution
- [x] address  import/no-duplicates warnings
- [x] fix last 3 eslint errors
- [x] if we adopt the plugin, mention on #213 that it's currently not compatible with ESLint 9

### CODE REVIEW

**Comment by jschuurk-kr** [comment]
@lkleuver Would appreciate your input on how to deal with the import/no-unresolved errors.

**Comment by praseodym** [comment]
Maybe the plugin doesn't resolve these paths from `tsconfig.json`?
https://github.com/kiesraad/abacus/blob/ee6a72f823585734f5393dc4636518e36152f3e2/frontend/tsconfig.json#L21-L29

**Comment by lkleuver** [comment]
This should resolve it, maybe.
https://www.npmjs.com/package/eslint-import-resolver-typescript

**Comment by praseodym** [comment]
> This should resolve it, maybe. https://www.npmjs.com/package/eslint-import-resolver-typescript

This issue comment also mentions that: https://github.com/import-js/eslint-plugin-import/issues/2765#issuecomment-1701641064

**Comment by praseodym** [comment]
I've fixed the remaining errors.

**Review by praseodym — APPROVED** [review]

**Review by Lionqueen94 — APPROVED** [review]

**Pull request merged**
