### PR TITLE
Prevent new data entry after finalisation

### LINKED ISSUE #316: Do not allow data entry save when already finalised
When the data entry for a polling stations is fully completed, we shouldn't allow new data entries to be saved for that polling station.

### PR DESCRIPTION
**Pull request by praseodym**
Resolves #316.

### CODE REVIEW

**Comment by praseodym** [comment]
d2d tests now fail because they expect to be able to do conflicting saves. We need to reset the database between tests (#318) to fix this.

**Comment by praseodym** [comment]
> d2d tests now fail because they expect to be able to do conflicting saves. We need to reset the database between tests (#318) to fix this.

Resolved by #327, so this PR is ready for review now.

**Review by Lionqueen94 — COMMENTED** [review]
Can you add a test for the new functionality?

**Comment by praseodym** [comment]
> Can you add a test for the new functionality?

Added in f1d02ff067fbfdd230b875b0af666f855db4a481.

**Review by Lionqueen94 — APPROVED** [review]

**Review by rnijveld — APPROVED** [review]

**Pull request merged**
